### ISSUE TITLE
event is undefined in o-carousel

### ISSUE THREAD

**Issue by lsnow99** [oruga-ui/oruga#264]
### Overview of the problem

Cannot use Vue router links inside `o-carousel-item` components.

**Oruga** version: 0.5.0
**Vuejs** version: 3.2.26
**OS/Browser**: Linux/Firefox

### Description

When using custom components for the carousel component, 

### Steps to reproduce

1. Add a o-carousel component
2. Add o-carousel-item components as children
3. Add a router-link component within them that links to another page
4. Error is produced in the beforeUnmount hook of o-carousel

Here is an example project that shows the bug: https://github.com/lsnow99/oruga-carousel-bug-demo

### Expected behavior

Successful navigation to next page

### Actual behavior

Page crashes with uncaught error:
```
[Vue warn]: Unhandled error during execution of beforeUnmount hook 
  at <OCarousel> 
  at <Home onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< null > > 
  at <RouterView> 
  at <App> runtime-core.esm-bundler.js:6620:16
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/vue-next 
  at <RouterView> 
  at <App> runtime-core.esm-bundler.js:6620:16
Uncaught (in promise) TypeError: event is undefined
    dragEnd carousel.js:364
    beforeUnmount carousel.js:402
    callWithErrorHandling runtime-core.esm-bundler.js:6737
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:6746
    __weh runtime-core.esm-bundler.js:1970
    invokeArrayFns shared.esm-bundler.js:541
    unmountComponent runtime-core.esm-bundler.js:4886
    unmount runtime-core.esm-bundler.js:4796
    unmountChildren runtime-core.esm-bundler.js:4924
    unmount runtime-core.esm-bundler.js:4814
    unmountComponent runtime-core.esm-bundler.js:4895
    unmount runtime-core.esm-bundler.js:4796
    patch runtime-core.esm-bundler.js:3760
    componentUpdateFn runtime-core.esm-bundler.js:4409
    run reactivity.esm-bundler.js:160
    callWithErrorHandling runtime-core.esm-bundler.js:6737
    flushJobs runtime-core.esm-bundler.js:6976
    promise callback*queueFlush runtime-core.esm-bundler.js:6867
    queueCb runtime-core.esm-bundler.js:6889
    queuePostFlushCb runtime-core.esm-bundler.js:6895
    queueEffectWithSuspense runtime-core.esm-bundler.js:1148
    scheduler runtime-core.esm-bundler.js:7176
    triggerEffects reactivity.esm-bundler.js:358
    triggerRefValue reactivity.esm-bundler.js:948
    effect reactivity.esm-bundler.js:1079
    triggerEffects reactivity.esm-bundler.js:358
    triggerRefValue reactivity.esm-bundler.js:948
    effect reactivity.esm-bundler.js:1079
    triggerEffects reactivity.esm-bundler.js:358
    triggerRefValue reactivity.esm-bundler.js:948
    set value reactivity.esm-bundler.js:992
    finalizeNavigation vue-router.esm-bundler.js:3187
    pushWithRedirect vue-router.esm-bundler.js:3060
    promise callback*pushWithRedirect vue-router.esm-bundler.js:3031
    push vue-router.esm-bundler.js:2962
    navigate vue-router.esm-bundler.js:2089
    callWithErrorHandling runtime-core.esm-bundler.js:6737
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:6746
    invoker runtime-dom.esm-bundler.js:357
    addEventListener runtime-dom.esm-bundler.js:307
    patchEvent runtime-dom.esm-bundler.js:325
    patchProp runtime-dom.esm-bundler.js:389
    mountElement runtime-core.esm-bundler.js:3905
    processElement runtime-core.esm-bundler.js:3868
    patch runtime-core.esm-bundler.js:3788
    componentUpdateFn runtime-core.esm-bundler.js:4339
    run reactivity.esm-bundler.js:160
    setupRenderEffect runtime-core.esm-bundler.js:4458
    mountComponent runtime-core.esm-bundler.js:4241
    processComponent runtime-core.esm-bundler.js:4199
    patch runtime-core.esm-bundler.js:3791
    mountChildren runtime-core.esm-bundler.js:3987
    processFragment runtime-core.esm-bundler.js:4158
    patch runtime-core.esm-bundler.js:3784
    mountChildren runtime-core.esm-bundler.js:3987
    mountElement runtime-core.esm-bundler.js:3896
    processElement runtime-core.esm-bundler.js:3868
    patch runtime-core.esm-bundler.js:3788
    componentUpdateFn runtime-core.esm-bundler.js:4339
    run reactivity.esm-bundler.js:160
    setupRenderEffect runtime-core.esm-bundler.js:4458
    mountComponent runtime-core.esm-bundler.js:4241
    processComponent runtime-core.esm-bundler.js:4199
    patch runtime-core.esm-bundler.js:3791
    mountChildren runtime-core.esm-bundler.js:3987
    processFragment runtime-core.esm-bundler.js:4158
    patch runtime-core.esm-bundler.js:3784
```

**Comment by astagi** [comment]
@lsnow99 thank you for reporting this issue! [This](https://github.com/oruga-ui/oruga/pull/265) fix should solve problems you're experiencing.

**Comment by jtommy** [comment]
@lsnow99 as workaround can you try to use `@click.stop` on `router-link`

**Comment by lsnow99** [comment]
Thank you @astagi for the quick fix! @jtommy that workaround did not work interestingly.

**Comment by astagi** [comment]
> Thank you @astagi for the quick fix! @jtommy that workaround did not work interestingly.

YW @lsnow99 I think that a min release is needed, will provide it asap

**Comment by astagi** [comment]
@lsnow99  0.5.2 released!
