### ISSUE TITLE
Nuxt3 Support

### ISSUE THREAD

**Issue by xxSkyy** [oruga-ui/oruga#281]
I've just found today Oruga and it's like best feature fulfill I'd imagine for tailwind/windi and I'd like to work with it, I'm working on vue 3 nuxt bridge and mostly Nuxt3. I tried to integrate it with Nuxt3 but no luck.
Are there a plan to support Nuxt3 and if so when is the estimated date?

Edit: I've seen roadmap and see it's planned so just asking about +/- when?

**Comment by jtommy** [comment]
What version are you using?

**Comment by xxSkyy** [comment]
I've checked again and it partly works, yday I just checked first examples and this ones don't work in nuxt3

First or second collapse code just don't work

```vue
<template>
  <section>
    <o-collapse :open="false" aria-id="contentIdForA11y1">
      <o-button variant="primary" aria-controls="contentIdForA11y1">Click me!</o-button>
      <div class="notification">
        <h3>
          Subtitle
        </h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br />
          Nulla accumsan, metus ultrices eleifend gravida, nulla nunc varius lectus, nec rutrum justo nibh eu lectus. <br />
          Ut vulputate semper dui. Fusce erat odio, sollicitudin vel erat vel, interdum mattis neque.
        </p>
      </div>
    </o-collapse>
  </section>
</template>

<script>
  export default {}
</script>

```

shows error

```
 ERROR  [worker] this.$slots.trigger is not a function                                                                             15:54:00

  at Proxy.render (node_modules/@oruga-ui/oruga-next/dist/esm/collapse.mjs:80:24)
  at renderComponentRoot (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:887:44)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:275:51)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
  at Module.ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
  at _sfc_ssrRender (.nuxt/dist/server/server.mjs:27780:31)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
  at renderVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)
  at renderVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:316:17)
```

but many of rest components works, I just copy pasted it but code looks fine

**Comment by jtommy** [comment]
The code in the docs works well ok Vue 2. 
For Vue 3, you should change slot declaration, for example wrap button into <template #trigger>

**Comment by xxSkyy** [comment]
Yup I see it, thanks
